### ISSUE TITLE
install error: jenkspy for python2

### ISSUE THREAD

**Issue by miriamrebekah** [mthh/jenkspy#19]
I'm trying to install jenkspy to work with python2. I'm using the `pip install jenkspy==0.1.1`. When I run this install, it fails. Is anyone else experiencing this?

`~/Desktop$ pip install jenkspy==0.1.1

Collecting jenkspy==0.1.1
  Using cached jenkspy-0.1.1.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/simulator/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vfns27rk/jenkspy_1c16cdd575934fbdb04c887234a13d9d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vfns27rk/jenkspy_1c16cdd575934fbdb04c887234a13d9d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-udmd59el
         cwd: /tmp/pip-install-vfns27rk/jenkspy_1c16cdd575934fbdb04c887234a13d9d/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vfns27rk/jenkspy_1c16cdd575934fbdb04c887234a13d9d/setup.py", line 22, in <module>
        ext_modules=cythonize(exts) if USE_CYTHON else exts,
      File "/home/simulator/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/home/simulator/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/simulator/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'jenkspy/src/jenks.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/ba/74e83afbef266b277f9fa293eb6e61e30c6d8515ab3c517beeeec71ad966/jenkspy-0.1.1.tar.gz#sha256=0cc09b9e0e9c7c99f00b834cac4e14a9e59d1f1a98ef5e014397f39c486310e5 (from https://pypi.org/simple/jenkspy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement jenkspy==0.1.1
ERROR: No matching distribution found for jenkspy==0.1.1
`

**Comment by mthh** [comment]
I can also confirm the error with my python 2.7 install.

Version 0.1.2 to 0.1.5 (included) should install / work fine with python 2.7.
Can you try it ?

**Comment by miriamrebekah** [comment]
Thank you! That worked!
