### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by mingchau** [mthh/jenkspy#3]
Hi @mthh:

Today I updated the Python version to 3.7.1, with using 
`pip install jenkspy`
Occurs 

> ImportError: cannot import name 'pythran_is_numpy_func_supported' from 'Cython.Compiler.Pythran' (C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\Pythran.cp37-win_amd64.pyd)

I did some googling, but unfortunately, there is no solution for this issue! So I'm opening this issue to see if you are going to update this lib? Thanks for your working :)

**Comment by mingchau** [comment]
FYI, the whole error message:

> Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8d9f5_ne\jenkspy\setup.py", line 32, in <module>
        ext_modules=cythonize(exts) if USE_CYTHON else exts,
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 947, in cythonize
        ctx = c_options.create_context()
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\Main.py", line 595, in create_context
        self.cplus, self.language_level, options=self)
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\Main.py", line 78, in __init__
        from . import Builtin, CythonScope
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\CythonScope.py", line 5, in <module>
        from .UtilityCode import CythonUtilityCode
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\UtilityCode.py", line 3, in <module>
        from .TreeFragment import parse_from_strings, StringParseContext
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\TreeFragment.py", line 17, in <module>
        from .Visitor import VisitorTransform
      File "Cython\Compiler\Visitor.py", line 17, in init Cython.Compiler.Visitor
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\ExprNodes.py", line 46, in <module>
        from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,
    ImportError: cannot import name 'pythran_is_numpy_func_supported' from 'Cython.Compiler.Pythran' (C:\Users\Administrator\Anaconda3\lib\site-packages\Cython\Compiler\Pythran.cp37-win_amd64.pyd)

**Comment by mthh** [comment]
Thanks for reporting this! I will investigate (unfortunately I don't have a windows platform near me - in case it's related).

Can you tell me what's your Cython version ?
It looks like it's related to how Cython is imported/used in the `setup.py` file (and maybe related to this issue : https://github.com/cython/cython/issues/2680).

By the way, you remind me that there is no wheel of jenkspy for python 3.7 on PyPI. 
I'll also fix that (so at least you will be able to install it directly from the wheel when doing `pip install jenkspy`).

**Comment by mingchau** [comment]
Hi @mthh:

Glad to hear your quick response!
I installed the Cython 0.29 on my Windows 10 (64bit) OS.

And the installation with the new wheel for Python 3.7 works well! Now all the codes running properly.
Problem solved. Wish you are going to have a nice weekend 👍

**Comment by mthh** [comment]
I guess what could have triggered this error is now fixed on cython side (and thanks to your issue, wheels of jenkspy are also available for python 3.7 now) so i'm closing this.
